post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRlbWFyIiwiaWQiOiI2MTQ5ZmY2MzE3NmFkYzU4YTVmYWE1YzAiLCJpYXQiOjE2MzI0NDA0NDd9.duZk_-j9skaN2VuT5v0h-SI7PLrg-5ZHNyZ7BBvz1Yo

{
   "title": "First Blog Post",
   "author": "Some author",
   "url": "www.someurl.com"
}